* SRFI 121: Generators

** by Shiro Kawai, John Cowan, and Thomas Gilray



keywords: [[https://srfi.schemers.org/?keywords=data-structure][Data Structure]], [[https://srfi.schemers.org/?keywords=r7rs-large-red][R7RS Large: Red Edition]], [[https://srfi.schemers.org/?keywords=superseded][Superseded]]

This repository hosts [[https://srfi.schemers.org/srfi-121/][SRFI 121]]: Generators, a [[https://srfi.schemers.org/][Scheme Request for Implementation]].

This SRFI is in /withdrawn/ status.

See also [[https://srfi.schemers.org/srfi-158/][SRFI 158: Generators and Accumulators]].

The full documentation for this SRFI can be found in the [[https://srfi.schemers.org/srfi-121/srfi-121.html][SRFI Document]].

If you'd like to participate in the discussion of this SRFI, or report issues with it, please [[https://srfi.schemers.org/srfi-121/][join the SRFI-121 mailing list]] and send your message there.

Thank you.

[[mailto:srfi-editors@srfi.schemers.org][The SRFI Editors]]

** CHICKEN specific files

=srfi-121.meta= : This file denotes metadata about the CHICKEN 4
extension, such as author, license, and dependencies (and dependencies
for tests).

=srfi-121.setup= : This file tells the CHICKEN 4 package manager
(=chicken-install=) how to build the egg.

=srfi-121.egg= : This is the input file for the package manager
(=chicken-install=) for CHICKEN 5.

=srfi-121.release-info= : Describes the URL / different releases of
the CHICKEN extension.

Additionally, the =tests/= directory has been added to accommodate the
CHICKEN package manager (for running tests).  Currently it provides a
default test runner which merely includes the tests found in the
=generators/= directory.

** License
Provided under a single clause BSD license, Copyright (C) John Cowan
2016.  See LICENSE for full details.

